### ISSUE TITLE
Wrong solution found

### ISSUE THREAD

**Issue by SamMackrill** [MathFreak314/DU-LUA-Ore-Finder#2]
This is working very well, except for my first ever attempt:
![image](https://user-images.githubusercontent.com/84898/97740318-02ac3e00-1ad9-11eb-803e-04c418f8fe98.png)

As you can see the waypoint is above ground :) Actual location was the mirror but underground.
All my scans were on the surface which was pretty flat (Madis)

**Comment by MathFreak314** [comment]
Ok, I think this one is just due to the limitations of what can be done.  Because I can't do a precise triangulation all I can do is narrow it down to a region in space that we best expect it to be.  After that it is a matter of determine what point in that region is our best guess for where it is.  Unfortunately there can be multiple points that fit that criteria and thus it can occasionally guess wrong.  However in general, if it guesses wrong the next measurement should correct it and as more measurements are added the guesses become better.

**Comment by SamMackrill** [comment]
Yeah, thought as much, feedback is always useful though :)
